#!/usr/bin/env python

import os, re

"""
Usage: python build_gen.py > build.sh
"""

OUTPUT_DIR = '../berkeley-cs61as.github.io/textbook/'
TEXTBOOK_DIR = 'textbook'
TEMPLATE = 'textbook.html'

def compile(input, output):
    print('templar compile "%s" -s "%s" -m -d "%s"' % (TEMPLATE, input, output))

def to_output_name(s, extension='.html'):
    s = re.sub('section\d* ', '', s)
    s = re.sub('\.md', '', s)
    s = re.sub('\.html', '', s)
    s = re.sub(',', '', s)
    s = re.sub(' - ', ' ', s)
    s = re.sub('\(', '', s)
    s = re.sub('\)', '', s)
    chunks = s.split(' ')
    chunks = map(lambda x: x.lower(), chunks)
    chunks = filter(lambda x: x, chunks)
    return '-'.join(chunks) + extension

print('#!/usr/bin/env bash')
print('# Generated by build_gen.py')

for d in os.listdir(TEXTBOOK_DIR):
    for f in os.listdir(os.path.join(TEXTBOOK_DIR, d)):
        compile(os.path.join(TEXTBOOK_DIR, d, f), os.path.join(OUTPUT_DIR, to_output_name(f)))



